Fix function producing multiple outputs
The function `slsa_build_scripted_build.trusted_build_task_error` could
produce more than one result if more than one `build_task_bundles` is
untrusted. For example when multiple tasks have the same, expected,
`IMAGE_DIGEST` result or if multiple tasks are in the same untrusted
bundle as the build task.

This changes the function to operate on tasks instead of bundles and to
concatenate any untrusted build task names, so when there are more than
one tasks with the expected `IMAGE_DIGEST` result -- a single error
message is returned.

This causes:

```
Error: 1 error occurred:
	* error validating image quay.io/redhat-appstudio-qe/enterprise-contract-tests:e2e-test-unpinned-task-bundle of component ec-cli: query rule: check: query rule: evaluating policy: /tmp/ec-work-556256966/policy/52241418b/policy/release/slsa_build_scripted_build.rego:161: eval_conflict_error: functions must not produce multiple outputs for same inputs
```

Caught by e2e tests in https://github.com/redhat-appstudio/infra-deployments/pull/2955